### ISSUE TITLE
Single Logout

### ISSUE THREAD

**Issue by fgather** [OpenConext/Mujina#15]
Hi,

is anyone interested in doing Single Logout with HTTP-POST and SOAP binding with Mujina? I could prepare a pull request.

**Comment by thijskh** [comment]
Hi! Pull requests are definitely welcome.

**Comment by fgather** [comment]
#16 I've created a PR

**Comment by oharsta** [comment]
Pull request locally resolved and pushed

**Comment by Itachi-Uchiha78** [comment]
What happened to the Single Logout? I'm in need of this function. thanks
