### ISSUE TITLE
Availability in maven central?

### ISSUE THREAD

**Issue by mattsheppard** [OpenConext/Mujina#17]
Is the any possibility of having Mujina available in maven central (to allow developers to depend on it without having to build and install it locally)?

I've been through the (admittedly kinda painful) process once or twice and would be happy to assist if needed - http://central.sonatype.org/pages/ossrh-guide.html

**Comment by thijskh** [comment]
@oharsta?

**Comment by oharsta** [comment]
We publish all OpenConext artefacts - including Mujina - to the OpenConext public available repositories:
```
<repositories>
     <repository>
            <id>openconext-releases</id>
            <name>OpenConext public releases repository</name>
            <url>https://build.openconext.org/repository/public/releases</url>
        </repository>
        <snapshotRepository>
            <id>openconext-snapshots</id>
            <name>OpenConext public snapshot repository</name>
            <url>https://build.openconext.org/repository/public/snapshots</url>
        </snapshotRepository>
</repositories>
```
You can either add them in your [pom.xml](https://maven.apache.org/guides/mini/guide-multiple-repositories.html) file or globally in your [~/.m2/settings.xml](https://maven.apache.org/settings.html).

**Comment by mattsheppard** [comment]
Ah, great - That'll do fine - Thanks!
