### ISSUE TITLE
Support running mujina-idp on ports other than 8080

### ISSUE THREAD

**Issue by mattsheppard** [OpenConext/Mujina#19]
It seems like mujina-idp is hard-coded to run on port 8080 - Though I can use `--server.port=8081` to have tomcat start on a different port, the metadata produced still refers to port 8080 (Seemingly from  https://github.com/OpenConext/Mujina/blob/master/mujina-idp/src/main/java/mujina/idp/MetadataController.java#L76)

It would be convenient, in an integration test scenario, to be able to select a free port at runtime and configure mujina-idp to use that.

**Comment by oharsta** [comment]
I agree with you that this would be a nice feature. Care to write a pull-request?

**Comment by mattsheppard** [comment]
Sure - I've never touched Spring-Boot before, but that seems to fix the case I was hitting in my environment.

From a quick grep, I don't immediately see other non-test, non-config places where 8080 has been hardcoded, but I've not tested it beyond what I needed.

**Comment by oharsta** [comment]
New 5.0.5 release: https://build.openconext.org/repository/public/releases/org/openconext/mujina-idp/5.0.5/

**Comment by mattsheppard** [comment]
Oh, wow, I didn't expect it to get released quite so quick - Thanks! :)

**Comment by LukeButtersFunnelback** [comment]
It seems that unless `application.yml` is also changed to have:
```
idp:
  entity_id: http://mock-idp
  # base url
  base_url: http://localhost:<SET PORT>
```
it wont work. Is it possible to override the values in `application.yml` when running the jar?
