### ISSUE TITLE
"validUntil" property in IdP metadata is set to past date

### ISSUE THREAD

**Issue by adunn8** [OpenConext/Mujina#24]
Currently the validUntil property is set to "2017-03-25T07:54:50.256Z".  

I've just removed it as a workaround, but you may want to consider doing the same in source.  Some frameworks (such as the one I use ;) ) will invalidate the metadata if its expired.  Not sure if there's a specific reason this was needed in the author's original implementation, but you may want to consider removing in source as its not a particularly useful feature for a testing tool.

**Comment by thijskh** [comment]
Because the metadata is a static file (right @oharsta?) it's probably best to remove the hardcoded `validUntil` and replace it with a long `cacheDuration` (because having one of those two is mandatory).

**Comment by oharsta** [comment]
Fixed in ead19337ed5ca2331a23066d9df70869dbb47540

**Comment by oharsta** [comment]
And this time correctly: a2255a4996e5f417af33fe277db270a3e68e7d99
