### ISSUE TITLE
Single Logout support

### ISSUE THREAD

**Issue by Itachi-Uchiha78** [OpenConext/Mujina#29]
Hi,

I need this feature, have you guys any project related to this argument?
If not, can anybody point me in the right direction to implement on my own?

thanks

**Comment by oharsta** [comment]
See the last comment in https://github.com/OpenConext/Mujina/pull/16. For a PR you could look at the original https://github.com/OpenConext/Mujina/pull/16/files and try to port it to the new code base.

**Comment by Itachi-Uchiha78** [comment]
I saw that code but it's pretty convoluted since this new Mujina is very optimized compared the old.
That said I've implemented my working SLO starting from SAML docs with very few instructions.
Still need to test with signed calls, but the flow works like a charm.

Thanks for the support and this Mujina!
