### ISSUE TITLE
Database support in IDP

### ISSUE THREAD

**Issue by shubham1205** [OpenConext/Mujina#38]
Any connectivity on IDP with jdbc or LDAP database in mujina???

**Comment by oharsta** [comment]
Nope. However there is a hook for implementing this in https://github.com/OpenConext/Mujina/blob/master/mujina-idp/src/main/java/mujina/idp/AuthenticationProvider.java#L22 and https://github.com/OpenConext/Mujina/blob/master/mujina-idp/src/main/java/mujina/idp/WebSecurityConfigurer.java#L146. See also this question -
 or the excellent Spring Security docs - on stack-overflow which explains the difference between a custom AuthenticationProvider versus a custom UserDetailsService
:https://stackoverflow.com/questions/31630818/spring-security-custom-authentication-authenticationprovider-vs-userdetailsser
