### ISSUE TITLE
Not Able to Run the project in Eclipse.

### ISSUE THREAD

**Issue by sourabhlodha** [OpenConext/Mujina#39]
Hi Team,
I am importing the Mujina Project as Maven Project.I am not able to run the project as it show me error.
I am attaching the screenshot.Can you provide me the step by step process to run project in eclipse.
![image](https://user-images.githubusercontent.com/11154338/39110860-654755dc-46f0-11e8-9dde-105003ab32f0.png)

**Comment by shubham1205** [comment]
Hi Sourabh,

If there are any errors occur in eclipse then attach *lombok jar* with
eclipse. Please refer below link for add *lombok jar*.

https://howtodoinjava.com/automation/lombok-eclipse-installation-examples/


Regards
Shubham

**Comment by sourabhlodha** [comment]
@shubham1205  That's Fine but can you provide the steps to run the project as I am not able to run the mujina project.

**Comment by sourabhlodha** [comment]
@shubham1205  Can you help me in providing solution as It seems to be error from jar side.
