### ISSUE TITLE
Create user at SP from IDP

### ISSUE THREAD

**Issue by maximonischenko** [OpenConext/Mujina#42]
Does Mujina IDP have an ability to provide linked SP with users? I'am asking about something like this https://www.ibm.com/developerworks/library/se-jitp/ `A just-in-time provisioning use case` part

**Comment by oharsta** [comment]
The JIT provisioning is for Service Providers who actually store the identity of the user. The Mujina SP was only developed to demonstrate the Mujina IdP and as such does not `do` anything with the user it receives in the SAML assertion. The Mujina IdP does has an API to add users on the fly: https://github.com/OpenConext/Mujina#adding-a-user.
