### ISSUE TITLE
Not Able to Debug SingleSignOnService

### ISSUE THREAD

**Issue by sourabhlodha** [OpenConext/Mujina#43]
Hi Team,
I want to debug the SingleSignOnService when I run Sp but not able to debug it. It directly shows me the index HTML without going on to debug point.

I also tried with the postman.

Can you please help me out in resolving this issue.

**Comment by oharsta** [comment]
I'm afraid I don't understand your question. With the help of an IDE and starting the Mujina-SP and Mujina-IdP in debug mode I'm capable of debugging the SAML login. See the README for more information on how to build and run the applications.
