### ISSUE TITLE
SAML extensions

### ISSUE THREAD

**Issue by roberttoja** [OpenConext/Mujina#48]
Hi, is there an option to add SAML Extensions to AuthnRequest?

**Comment by oharsta** [comment]
It is possible. Have a look at the commit https://github.com/OpenConext/Mujina/commit/b82adb00a1e6469322e02ebe448c29066523d1b8 in the branch https://github.com/OpenConext/Mujina/tree/feature/SAMLExtensions. It uses a custom [WebSSOProfile](https://github.com/OpenConext/Mujina/blob/feature/SAMLExtensions/mujina-sp/src/main/java/mujina/sp/WebSSOProfileExtensions.java) which adds an `Extensions` element to the `AuthnRequest`:
```
<md:Extensions xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata">
        <policy:Policy policyAttribute="value" xmlns:policy="https://openconext/schema/ext">urn:type:policy:consent</policy:Policy>
    </md:Extensions>
```
The custom `WebSSOProfile` is wired in https://github.com/OpenConext/Mujina/blob/feature/SAMLExtensions/mujina-sp/src/main/java/mujina/sp/SAMLConfig.java#L159

**Comment by roberttoja** [comment]
Hi,
thanks for your help. I need to produce something like this in extensions

<saml2p:Extensions><eidas:RequestedAttributes xmlns:eidas="http://eidas.europa.eu/saml-extensions">
<eidas:RequestedAttribute Name="http://host/attributes/naturalperson/CurrentGivenName" NameFormat="urn:pl:kir:wb:names:SAML:2.0:attrname-format:uri" isRequired="true"/><eidas:RequestedAttribute Name="http://host/attributes/naturalperson/CurrentFamilyName" NameFormat="urn:pl:kir:wb:names:SAML:2.0:attrname-format:uri" isRequired="true"/><eidas:RequestedAttribute Name="http://host/attributes/naturalperson/PersonIdentifier" NameFormat="urn:pl:kir:wb:names:SAML:2.0:attrname-format:uri" isRequired="true"/></eidas:RequestedAttributes>
<xyz:OperationContext xmlns:xyz="http://host/saml-extensions"><xyz:ContextClass>PERSONAL_IDENTIFICATION_ATTRIBUTES</xyz:ContextClass><xyz:ContextDescription>Rejestracja w serwisie DU1</xyz:ContextDescription></xyz:OperationContext></saml2p:Extensions><saml2p:NameIDPolicy AllowCreate="true" Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"/><saml2p:RequestedAuthnContext Comparison="minimum"><saml2:AuthnContextClassRef>http://eidas.europa.eu/LoA/low</saml2:AuthnContextClassRef></saml2p:RequestedAuthnContext>

Are you able to guide me a little?

Many thanks
