### ISSUE TITLE
Query about production usage

### ISSUE THREAD

**Issue by Panchjanya** [OpenConext/Mujina#56]
Sorry for asking this question without reading the complete code-base.  

May I know if this project can be used in production ?   
(The reason for asking this question is in the description, it says **mock** IDP)  

Is it just a mock or provide all the mentioned functionalities as it is as mentioned in the description. 

Thanks

**Comment by pmeulen** [comment]
Hi Panchjanya,

I'm not sure I understand your question. Mujina provides all the functionalities that are described in the README.md. Mujina is a real SAML IdP and SP that is intended for testing, e.g. creating automated integration tests where it can be scripted to behave as a SAML IdP and/or SP. It is not intended to be used as an IdP or SP for authenticating real users, so in that sense it is a "mock".

**Comment by Panchjanya** [comment]
Hi @pmeulen   
> It is not intended to be used as an IdP or SP for authenticating real users, so in that sense it is a "mock"   

Got it. Thank you for the clarification. 

Background :   
Actually, I have to create an IdP for my own usage. And I was looking for some open source implementation using Java. That's why I wanted to confirm if it can be used in production for real users.
