### ISSUE TITLE
Do you provide a docker image ?

### ISSUE THREAD

**Issue by FreifeldRoyi** [OpenConext/Mujina#57]

**Comment by corjanbos** [comment]
Hi,

Maybe the following project may be of any help.

https://github.com/olesu/docker-mujina

Good luck!

**Comment by FreifeldRoyi** [comment]
I was curious if you have an official docker image

**Comment by corjanbos** [comment]
Hi, 
I don't think OpenConext will publish a Docker image because that seems out of scope here, and you would nevertheless have to make a lot of custom settings in order to make your Idp and SP work.

**Comment by FreifeldRoyi** [comment]
Reasonable.
Thank you for the link! I'll definitely check it out
