### ISSUE TITLE
Integrating Mujina-idp with End System Applications( ex: Java SpringBoot , Java Micro services or Java Based CMS)

### ISSUE THREAD

**Issue by devendar-12** [OpenConext/Mujina#59]
Hi , 

I have a requirement that, i wanted to implement Mujina with my existing End user application. I have 3 different end user applications, mainly focusing on implementing SSO between Mujina-idp ( with dummy users) to Clone of a PROD CMS application.

Can i completely replace mujina-sp and change the configuration files of mujina-idp yml.properties and the End user CMS Application?

Or, do i need to write any intermediate application to communicate with mujina-idp &  SP ( CMS Application).?

Your help on this will be much appriciated.

Thanks

**Comment by oharsta** [comment]
You can fork Mujina and delete everything related to the SP. Nothing related to the IdP depends on the SP. Your CMS application can _talk_ directly to the Mujina IdP - no intermediate application is needed.

Do note that this code base was developed for testing purposes and not for running as a _real_ IdP. If you still want to run this in production you will want to disable the IdP API and do something meaningful in https://github.com/OpenConext/Mujina/blob/master/mujina-idp/src/main/java/mujina/idp/SsoController.java#L86.

**Comment by devendar-12** [comment]
Thanks for your help with this!!.
