### ISSUE TITLE
In which Maven repository is nl.iprofs.modules.context-logging:context-logging:jar ?

### ISSUE THREAD

**Issue by EvaPawlowskiBit** [OpenConext/Mujina#6]
I am trying to build mujina with mvn clean install.
I could not find any repository with nl.iprofs.modules.context-logging:context-logging:jar:1.2.5.
Could you tell me were I should look?
Eva

**Comment by thijskh** [comment]
Hi Eva, 
It's available from https://build.surfconext.nl/repository/public/third-party/nl/iprofs/modules/context-logging/context-logging/
When I run `mvn clean install`, this dependency is automatically found and downloaded there.

**Comment by EvaPawlowskiBit** [comment]
Hi Thijs

Many thanks – that was the reason.
In our nexus, your repo is not fully mapped and I could not find the correct path via google.
Maybe putting the repository pathes into the REAME would help outsiders.

Many thanks
Eva

Von: Thijs Kinkhorst [mailto:notifications@github.com]
Gesendet: Mittwoch, 29. Juli 2015 13:46
An: OpenConext/Mujina
Cc: Pawlowski Eva BIT
Betreff: Re: [Mujina] In which Maven repository is nl.iprofs.modules.context-logging:context-logging:jar ? (#6)


Hi Eva,
It's available from https://build.surfconext.nl/repository/public/third-party/nl/iprofs/modules/context-logging/context-logging/
When I run mvn clean install, this dependency is automatically found and downloaded there.

**Comment by thijskh** [comment]
Updated the README with that info now.
Let me know if you're missing anything else.

**Comment by EvaPawlowskiBit** [comment]
Many Thanks from Switzerland ☺

Von: Thijs Kinkhorst [mailto:notifications@github.com]
Gesendet: Donnerstag, 30. Juli 2015 12:18
An: OpenConext/Mujina <Mujina@noreply.github.com>
Cc: Pawlowski Eva BIT <Eva.Pawlowski@bit.admin.ch>
Betreff: Re: [Mujina] In which Maven repository is nl.iprofs.modules.context-logging:context-logging:jar ? (#6)


Updated the README with that info now.
Let me know if you're missing anything else.
