### ISSUE TITLE
In IDP where to configure the SP-metadata.xml file ?

### ISSUE THREAD

**Issue by nikhilpatil9099** [OpenConext/Mujina#78]
Respected @oharsta,
It was great to work with the custom IDP and SP code which you have provided on GitHub, I have one issue that where to configure the SP meta-data.xml file in the IDP project in the application.yml  file as we configured the IDP metadata.xml file in the SP project in application.yml file but in IDP we have not configured the sp metadata.xml file. so please can you help me out with how to configure sp metadata.xml in IDP.

Any leads will be appreciated.
Thanks in advance

**Comment by oharsta** [comment]
In the current setup the SP knows about the IdP, but the IdP does not know about the SP. The assertion is send back to the ACS location in the authnRequest. If you want the IdP to know about the SP (why?) then you would have to implement that.

**Comment by nikhilpatil9099** [comment]
Yes, I got that point. but I want to implement the direct SAML response from IDP  to SP without SP SAML request so I want to try to implement that the IDP should know about SP. can you please help me out for implementing the SP metadata configuration in IDP. it will be a big help.

Please check the above code I am trying for implementing in IDP for SP metadata URL (IDP should know about SP).


```
@Value("${idp.sp_metadata_url}")
private String ServiceProviderMetadataURL;  

@Bean
public MetadataProvider serviceProvider() throws MetadataProviderException, XMLParserException {
  Resource resource = defaultResourceLoader.getResource(ServiceProviderMetadataURL);
  ResourceMetadataProvider resourceMetadataProvider = new ResourceMetadataProvider(resource);
  resourceMetadataProvider.setParserPool(parserPool());
  ExtendedMetadataDelegate extendedMetadataDelegate = new ExtendedMetadataDelegate(resourceMetadataProvider, extendedMetadata());
  extendedMetadataDelegate.setMetadataTrustCheck(true);
  extendedMetadataDelegate.setMetadataRequireSignature(true);
  return extendedMetadataDelegate;
}

@Bean
@Qualifier("metadata")
public CachingMetadataManager metadata() throws MetadataProviderException, XMLParserException {
  List<MetadataProvider> providers = new ArrayList<>();
  providers.add(serviceProvider());

  return new CachingMetadataManager(providers);
}
```
I am trying to implement the same as you have done in SP for configuring IDP metadata URL. 
is this way right..?
Please help me out. it will be really great help.
Any leads will be appreciated.
Thanks in advance

**Comment by oharsta** [comment]
What you are looking for is described here: https://docs.spring.io/spring-security-saml/docs/current/reference/html/configuration-sso.html#configuration-sso-process-idp-init

You do not need the SP XML metadata at the IdP for that, only the ACS of the SP.

**Comment by nikhilpatil9099** [comment]
> What you are looking for is described here: https://docs.spring.io/spring-security-saml/docs/current/reference/html/configuration-sso.html#configuration-sso-process-idp-init
> 
> You do not need the SP XML metadata at the IdP for that, only the ACS of the SP.

Thanks for the reference link and reply..!
I tried but I am not getting it. stuck with some issues.  can you help me out with the java configuration of SP metadata in IDP.
As I want to implement on IDP actually SP is already implemented. just accessing the  SP through IDP. I trying to implement the IDP-initiated SSO. almost done only not getting of configuring SP metadata.xml in IDP. can you please help me out with java configurations. when I click the login button I should directly redirect to SP and send the response of attributes.
@oharsta Thanks 
Any leads will be appreciated.
