### ISSUE TITLE
Enable SHA 256 assertion signing

### ISSUE THREAD

**Issue by thijskh** [OpenConext/Mujina#9]
Mujina currently hardcodes signing assertions with SHA-1. SP's are starting to phase that out in favour of more modern hashing algorithms, so Mujina should support those. At least SHA-256 is needed. It would be best if this would be a configurable option.

**Comment by oharsta** [comment]
https://github.com/OpenConext/Mujina/commit/ae2df7799e9b6aee003c4d6ad6194e5c6dca708f

**Comment by oharsta** [comment]
https://build.surfconext.nl/repository/public/releases/org/surfnet/coin/mujina-idp/4.1.1/
